name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.IMAGE_NAME }}:${{ github.sha }} .
          docker tag ${{ secrets.IMAGE_NAME }}:${{ github.sha }} ${{ secrets.IMAGE_NAME }}:latest
      - name: Push Docker image to Amazon ECR
        run: |
          docker push ${{ secrets.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ secrets.IMAGE_NAME }}:latest
